### ISSUE TITLE
"Exit" feature for players.

### ISSUE THREAD

**Issue by Heng-Zi-Hui** [ETI-Oct2020-Team1/DevOpsRepo#13]
This feature is to allow users to leave the game when they want to stop playing. 
- [x] Check if player wants to save before exit
- [x] quit()
- [x] Create link to feature for #10 
- [x] Create link to feature for #5 
- [x] Create link to feature for #3
